### ISSUE TITLE
How to use fzf popup ?

### ISSUE THREAD

**Issue by pythops** [wfxr/tmux-fzf-url#10]
Thanks for this great plugin.
Currently, the urls are displayed in a tmux pane, is it possible to make display them in a popup ?

**Comment by wfxr** [comment]
I think it's possible but the plugin doesn't support for now. Welcome to contribute!

**Comment by nifr** [comment]
I have sent PR #16  that implements the option to pass custom fzf options :)

**Comment by wfxr** [comment]
PR merged. Thank you! @nifr
