### ISSUE TITLE
Latest version doesn't seem to work?

### ISSUE THREAD

**Issue by h0adp0re** [wfxr/tmux-fzf-url#12]
I can't get it to work, is the load order of plugins somehow significant?

I have `fzf` installed via Homebrew and in my `$PATH`, I can use it and do use it in other scripts.

**Comment by wfxr** [comment]
Can't repro. Are you sure the plugin has been sourced by tmux correctly?

**Comment by h0adp0re** [comment]
yeah, I mean it's just this, right? is the order important? are there plugins that conflict with this one?
```tmux
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-open'
# set -g @plugin 'tmux-plugins/tmux-urlview'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'aaronlna/tmux-plugin-sysstat'
set -g @plugin 'narugit/tmux-temp-mac'
set -g @plugin 'wfxr/tmux-fzf-url'
```

**Comment by wfxr** [comment]
Weird. You can try the following steps to debug:

1. `cd ~/.tmux/plugins/tmux-fzf-url` (where the plugins located in, modify the path if you used a different location)
2. `echo https://google.com` (to print a url for testing)
3. `./fzf-url.sh` (call the script directly)

If it works I guess you or some other plugin maybe overwrite the keybind.

**Comment by h0adp0re** [comment]
`brew install bash` fixed it, thanks for the plugin, it's very handy

**Comment by d1egoaz** [comment]
would be great to add this to the readme, MacOS uses a very old bash version
