### ISSUE TITLE
Allow for configuring fzf

### ISSUE THREAD

**Issue by h0adp0re** [wfxr/tmux-fzf-url#13]
Any way to configure fzf used by this plugin? Looks like it's invoked via bash. I don't use bash, I use zsh. Should I start maintaining a `.bash_profile` or is there a simpler way?

**Comment by wfxr** [comment]
@h0adp0re You don't need care about the script language. No matter which shell you use, the script can execute correctly since bash is installed default on most Linux distributions and osx. You should make sure your `PATH` environment variable contains the location of `fzf`.

**Comment by h0adp0re** [comment]
I think you misunderstood me. Everything works just fine but I can't customize fzf – my env variables don't take effect. For example - https://github.com/junegunn/fzf/wiki/Color-schemes

**Comment by h0adp0re** [comment]
The idea is more clearly described in #15.

**Comment by h0adp0re** [comment]
> No matter which shell you use, the script can execute correctly since bash is installed default on most Linux distributions and osx.

That's not entirely true, either. You're using `mapfile` and `bash 3.2` doesn't have that function. macOS (at least mine, 11.3, latest at this moment) ships with `bash 3.2`. I suggest you look into a more robust solution, something like [this](https://stackoverflow.com/questions/41475261/need-alternative-to-readarray-mapfile-for-script-on-older-version-of-bash), perhaps.

**Comment by wfxr** [comment]
> I think you misunderstood me. Everything works just fine but my customizations to fzf – my env variables – don't take effect as they have done elsewhere I've used fzf. For example - junegunn/fzf/wiki/Color-schemes

@h0adp0re Now I understand what you mean. But env variables are also not related to the shell. I don't known why your env variables don't take effect?

**Comment by wfxr** [comment]
Have you export the `FZF_DEFAULT_OPTS` variable correctly?

```sh
zsh shell> export foo=bar # export foo in zsh
zsh shell> bash           # run bash shell
bash shell> echo $foo     # $foo still accessable, so does the `FZF_DEFAULT_OPTS`
bar
```

**Comment by h0adp0re** [comment]
> But env variables are also not related to the shell. I don't known why your env variables don't take effect?

It appears you're right. I can echo my `$FZF_DEFAULT_OPTS` both in zsh and bash... I don't know why I thought they're shell-specific, that doesn't make any sense hehe.

> Have you export the `FZF_DEFAULT_OPTS` variable correctly?

I'm quite sure, yes. I've just exported it in `.zshrc`, it works when fzf is invoked via the shell.
```sh
export FZF_DEFAULT_OPTS="--color='prompt:#e78a4e,gutter:-1,pointer:#89b382,bg+:#45403d' --cycle --prompt='❯ ' --pointer='▶'"
```

**Comment by wfxr** [comment]
Weird. Can you try to kill the tmux server and restart to test again? If you didn't start your tmux server in your login shell(eg. autostart tmux server by crontab or systemd or something similiar), it won't read zsh's configurations so the environment variables for the tmux is not the same as your zsh shell.

**Comment by h0adp0re** [comment]
Nope, killing the server didn't help.

**Comment by wfxr** [comment]
![image](https://user-images.githubusercontent.com/6105425/120133336-8f99b000-c1fe-11eb-80b4-b8576871c87e.png)

Work fine for me.

Can you go to the plugin directory and run the `fzf-url.sh` directly to test?
```sh
./fzf-url.sh
```

**Comment by maniac-en** [comment]
I'm facing the same issues. I don't get my default fzf opts while using the keybind but if I run `fzf-url.sh` directly, it uses the default opts.

**Comment by wfxr** [comment]
@maniac-en What's the output of the following commands?

1.
```sh
echo $SHELL # test it both in zsh & bash
```
2.
```sh
tmux show -gqv default-shell
```

**Comment by h0adp0re** [comment]
> I'm facing the same issues. I don't get my default fzf opts while using the keybind but if I run `fzf-url.sh` directly, it uses the default opts.

I had the same result.

1. `echo $SHELL` strangely has the same result in both shells:
```
/usr/local/bin/zsh
```

2. `tmux show -gqv default-shell`
```
/usr/local/bin/zsh
```

**Comment by maniac-en** [comment]
It's `zsh` everywhere!

![7Qt4gA2](https://user-images.githubusercontent.com/45049766/120170119-448f9500-c21e-11eb-998b-581303e306ad.png)

**Comment by wfxr** [comment]
@maniac-en The output is exactly the same as me. But I don't have the problem. WHY :rofl:

**Comment by h0adp0re** [comment]
@maniac-en try moving your environment variables to `.zshenv` instead of `.zshrc`. My situtation got fixed once I did that.

**Comment by nifr** [comment]
Happy every day `tmux-fzf-url` user here ;)

I'd also love to see an option to configure the options passed to `fzf-tmux`.

I would like to use the popup function introced in tmux 3.2+ for `tmux-fzf-url` but with a different set of options than my `FZF_DEFAULT_OPTS`.

Right now the options are hardcoded  in [`fzf-url.sh`](https://github.com/wfxr/tmux-fzf-url/blob/f338301bd6de59efae91746e5bbac4b0c09a1639/fzf-url.sh#L8):

```
fzf_filter() { 
   fzf-tmux -d 35% -m -0 --no-preview --no-border 
}
```

In order to make them configurable i would suggest the introduction a new tmux option `@fzf-url-fzf-options`. 

Please see my PR #16 :)

**Comment by h0adp0re** [comment]
@nifr thank you, this is precisely what promped me to open this issue. Although I've since solved the problem I was having, I will enjoy customizing the popup size via the added feature.

**Comment by wfxr** [comment]
@nifr @h0adp0re @maniac-en 

The PR has been merged. Thanks for your contribution!
