### ISSUE TITLE
Feature-request: read the environment variable "$FZF_DEFAULT_COMMAND"

### ISSUE THREAD

**Issue by maniac-en** [wfxr/tmux-fzf-url#15]
If user wants fzf for this plugin to look different than the default layout, they could set `@fzf-url-default-command` in their tmux config. 

This would even let the user to replicate the system's fzf default command like this:

```
set -g @fzf-url-default-command "$FZF_DEFAULT_COMMAND"
```
> I'm not sure if this works though!

**Comment by h0adp0re** [comment]
This seems like a duplicate of #13.

**Comment by maniac-en** [comment]
> This seems like a duplicate of #13.

Closing this since we can discuss it in #13 itself.

**Comment by h0adp0re** [comment]
@maniac-en try exporting your environment variables in `.zprofile`. This ensures every session that is started has them set.

**Comment by maniac-en** [comment]
> try exporting your environment variables in `.zprofile`. This ensures every session that is started has them set.

I actually wanted a different fzf behaviour rather than my system wide fzf settings, and #16 has helped me do that. Thanks for the suggestion anyways!

**Comment by h0adp0re** [comment]
@maniac-en ah, of course. i've misread the problem. but sure, i hope the new knowledge helps you in the future!
