### ISSUE TITLE
Tmux-popup not working for me. Does it still work with tmux 3.3?

### ISSUE THREAD

**Issue by eggbean** [wfxr/tmux-fzf-url#22]
As mentioned in the README.md, I have added this line to my tmux config:

```
# open tmux-fzf-url in a tmux v3.2+ popup
set -g @fzf-url-fzf-options '-w 50% -h 50% --multi -0 --no-preview --no-border'
```

While any configuration changes to change the appearance of fzf, it's not in a tmux popup as mentioned in the comment. How do I make it into a centralised popup? I'm using tmux 3.3 on Linux.

**Comment by DanielSiepmann** [comment]
I've tmux 3.3a and the following config:
```
set -g @fzf-url-fzf-options '-p -y 1 -w 95% -h 75%'
```

this works fine for me for https://github.com/wfxr/tmux-fzf-url/commit/1241fc5682850fe41812cad81c76541674ee305b which is the latest state available in nix.

**Comment by eggbean** [comment]
Thanks for the reply, but I did get it working after I made this issue. I'm currently using:

`set -g @fzf-url-fzf-options '-w 50% -h 60% --multi -0 --no-preview --layout reverse --prompt "url: " --no-info --pointer ● --color "prompt:#bd93f9,pointer:#bd93f9"'`

**Comment by DanielSiepmann** [comment]
Maybe you can close the issue then @eggbean ? :)

**Comment by eggbean** [comment]
Ha, oh yeah..
