### ISSUE TITLE
Invalid URL Parsing

### ISSUE THREAD

**Issue by albertilagan** [wfxr/tmux-fzf-url#33]
Issue in parsing links from tmux config includes quotation marks which results in opening a 404 github page.
<img width="603" alt="image" src="https://github.com/wfxr/tmux-fzf-url/assets/22500561/d20e89e5-253c-475d-a30f-b13d33e67a3b">

**Comment by wfxr** [comment]
Hi @albertilagan, this should be fixed by @suweller in https://github.com/wfxr/tmux-fzf-url/pull/30.
