### ISSUE TITLE
How many urls will be displayed for a file

### ISSUE THREAD

**Issue by RiteshChepuri** [wfxr/tmux-fzf-url#34]
I tried to open urls in my plugins.lua in neovim. Its showing only like 8 links to open. What is the limit and how do i increase the limit?

**Comment by wfxr** [comment]
@RiteshChepuri There is no explicit limit, but the plugin only captures urls at the current pane. You can change this behavior by setting `history_limit` to capture the scrollback history:

```tmux
set -g @fzf-url-history-limit '2000'
```
