### ISSUE TITLE
Add support for OSC 8 Hyperlinks

### ISSUE THREAD

**Issue by DovieW** [wfxr/tmux-fzf-url#38]
For example, you can add `echo -e "\033]8;;https://www.google.com\aGoogle\033]8;;\a"` to a script to try it out.
It's a hidden URL.

**Comment by wfxr** [comment]
Thank you @DovieW, this would be a nice addition! I have tried to implement it in #42. Can you help test it?

**Comment by DovieW** [comment]
Thank you for implementing it.
I've checked out the branch and restarted tmux, but I'm not seeing it working.

I'm on tmux version 3.4 and have the config `set -ga terminal-features "*:hyperlinks"` set. But it doesn't seem that tmux is supporting hyperlinks. How did you get it to work?

**Comment by DovieW** [comment]
Nevermind it is working. Testing it now

**Comment by DovieW** [comment]
It works! My use case was for using it with git-delta's hyperlink feature.

**Comment by wfxr** [comment]
> It works! My use case was for using it with git-delta's hyperlink feature.

Thank you for letting me known hyperlink feature of git-delta!
