### ISSUE TITLE
it doesn't work anymore?

### ISSUE THREAD

**Issue by GopherJ** [wfxr/tmux-fzf-url#8]
Hi, I have been using this plugin for a while, it's absolutely great! However, recently it suddently stopped working, while I press `c+b+u` it doesn't give me anything, is there any upstream changes? How can I make it work?

**Comment by wfxr** [comment]
Tested it under variant OSs and all works fine.

As you can see, the most recent update of this project was 4 months ago. So I think the problem may be caused by your tmux / fzf binary or configurations?

To debug you can go to the plugin directory and run `fzf-url.sh` directly.

**Comment by GopherJ** [comment]
strange it works if I execute it alone

**Comment by GopherJ** [comment]
ok I understood this happens since alacritty@0.6
